server:
 port: 8082
logging:
 config: classpath:logback-boot.xml

###################################
###Mapper.xml
################################### 
mybatis:
 config-location: /mapper/*.xml
 type-aliases-package: site.acacia.flea.pojo

###################################
###Mysql
###################################
spring:
 datasource:
  username: root
  password: root
  url: jdbc:mysql://192.168.0.1:3306/flea?useUnicode=true&characterEncoding=utf-8
  driver-class-name: com.mysql.jdbc.Driver
  initialSize: 5
  minIdle: 5
  maxActive: 20 
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
 http:
  encoding:
   force: true
 redis:
   host: 192.168.0.1
   port: 6379
   database: 1
   pool:
    max-active: -1
    max-wait: -1
    max-idle: 10
    min-idle: 0
   timeout: 0
